In [3]:
import numpy as np 
import matplotlib as mb 
import pandas as pd

In [12]:
arr1 = np.array([1,2,4,5]) 
print(arr1)  

n = np.zeros(5) 
print(n) 

k = np.ones(5) 
print(k)

for i in arr1: 
    print(i)  

print(arr1.shape)

[1 2 4 5]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
1
2
4
5
(4,)


In [ ]:
arr1 = np.array([2,5,10, 3,4 ])  


print("Max value in the array:", np.max(arr1))
print("Sorting array:" , np.sort(arr1))

Max value in the array: 10
Sorting array: [ 2  3  4  5 10]
